### ISSUE TITLE
Site does not sign out

### ISSUE THREAD

**Issue by dansteele** [codebar/planner#648] opened 2017-12-15 11:49 UTC
## Description of the issue 📄
1) Sign in
2) Click menu > sign out
3) ✅ Correctly taken to the homepage
4) ✅ Sign in button visible
5) Click 'Sign in'
6) 🚫 ❗️ Immediately taken to dashboard without authentication

It seems like the session being properly invalidated, though I haven't taken a proper look (yet)

**Comment by skattyadz** [comment] 2018-01-11 06:18
If you try to access the [dashboard page](http://codebar.io/dashboard) after signing out you'll see that it is behaving as expected. It looks like this is more of a UX problem.

The site uses GitHub for auth so if you're logged in on GitHub your codebar log in will happen very quickly with no intermediate step. It's actually so fast it's a bit jarring!

Also it doesn't look like there's a sign out flash at the moment

**Comment by despo** [comment] 2020-05-20 20:43
Closing as this is the expected behavior as per @codeincontext's comment.

**Closed by despo** 2020-05-20 20:43 UTC
