### ISSUE TITLE
Tidy up models - Meeting, MeetingTalk, Sessions, SessionInvitation, Invitation

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#319] opened 2015-09-02 18:59 UTC
`Meeting` has only been used twice, once in 2013 and once in 2014. Neither of these pages load on the production site. Suggest `Meeting` and `MeetingTalk` should be deleted and references removed.

`Sessions` should really be called `Workshop` _plural_, with `SessionInvitation` becoming `WorkshopInvitation`.

`Invitation` is used, but only for `events`. If we want to keep the invitations for sessions (workshops) and events separate, then perhaps `Invitation` should become `EventInvitation`. Won't be the most tidy/DRY design but it'll at least be intuitive.

**Comment by heruku** [comment] 2015-09-03 15:56
@matyikriszta Should the database tables be dropped for meetings and meeting_talks as well?

**Comment by matyikriszta** [comment] 2015-09-09 18:48
@heruku sorry for the late response, yes, I think we can go ahead and drop those as well

**Comment by deniseyu** [comment] 2015-09-15 09:23
@heruku @matyikriszta it might make sense to use single-table inheritance for event invitations and session invitations since the only difference is that events might contain a few extra fields such as questionnaire links and ti.to webhook urls

**Comment by stschwark** [comment] 2015-10-22 09:23
PR #325 addresses the requirement from the first paragraph.

This leaves three event types: courses, workshops and events.

There are a good number of events and workshops in the diary this year but not a single course. Makes me wonder whether the Course model remains relevant for the future of Codebar?

Also I think the big question here is what @deniseyu raised above: Should these different event types be modelled separately or converge into a single model? Abstraction vs specialisation.

**Comment by matyikriszta** [comment] 2015-10-22 11:02
@stschwark @deniseyu I've been thinking about this and yes, we are planning to put on a iOS course early next week that would be a 5 evening series of workshops, for that a Course model would be relevant where you can add more than one date and possibly more than one host/venue to it 

also, might be worth having a Meeting model, this would be for more social types of events like our Christmas party. Currently when you create an event you have to specify a host, but with our Christmas party we have no host. It would essentially be a simplified Event with only date, description and venue (maybe organisers). This of course could inherit from the Session invitations model

Just a couple of things to think about...

**Comment by deniseyu** [comment] 2015-10-23 14:10
@matyikriszta @stschwark I think something for social events would be useful. Event model by design is currently quite strict with validations.

It should be called something more intention-revealing though, like 'Social' :-)

**Comment by stschwark** [comment] 2015-10-26 21:06
@matyikriszta @deniseyu Each event type currently is like a mini application with it's own views, controllers, mailers, models, etc. and I found it quite hard to make out which bits belong to which event type. This will also get harder with each event type that is added into the mix. I guess we could either try to separate them better or work towards a design that doesn't require as much duplication. Getting together to discuss might help as well.

**Comment by despo** [comment] 2018-05-19 23:45
I think this is no longer relevant since most models have been renamed and meetings are utilised in a different way. Closing.

**Closed by despo** 2018-05-19 23:45 UTC
