### ISSUE TITLE
Faulty donate pop up

### ISSUE THREAD

**Issue by Kalok9990** [codebar/planner#663] opened 2018-01-24 16:35 UTC
## Description of the issue 📄

When trying to donate and click on the button to call the pop up to enter the bank details, it does not always pop up and allow the user to enter the details (even upon repetition of clicking the button).

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment] 2018-06-04 21:04
Hi @Kalok9990, thanks for bringing this to our attention, this is possibly a duplicate of #699 which is now fixed. Going to close this issue.

**Closed by matyikriszta** 2018-06-04 21:04 UTC
